version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6380:6379"
    networks:
      - image-processing-network

  image-processing-api:
    build:
      context: ./image-processing-api
    container_name: image-processing-api
    env_file:
      - ./image-processing-api/.env
    ports:
      - "5858:8000"
    depends_on:
      - redis
    networks:
      - image-processing-network

  image-processing-worker:
    build:
      context: ./image-processing-worker
    env_file:
      - ./image-processing-worker/.env
    depends_on:
      - redis
    networks:
      - image-processing-network
    deploy:
      replicas: 3

networks:
  image-processing-network:
    driver: bridge
